# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - web-app-actions

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      ###testes
      - name: Testes unitários
        run: dotnet test ./test/JornadaMilhas.Unity.Test
        
      - name: Testes de Integração
        run: dotnet test ./test/JornadaMilhas.Integration.Test.API
        
      ###build
      - name: Restore do Projeto de API
        run: dotnet restore ./src/JornadaMilhas.API
      - name: Restore do Projeto de Dados
        run: dotnet restore ./src/JornadaMilhas.Dados
      - name: Restore do Projeto de Domínio
        run: dotnet restore ./src/JornadaMilhas.Dominio
      - name: Build projeto de API
        run: dotnet build ./src/JornadaMilhas.API --no-restore
      - name: Build projeto de Dados
        run: dotnet build ./src/JornadaMilhas.Dados --no-restore
      - name: Build projeto de Domínio
        run: dotnet build ./src/JornadaMilhas.Dominio --no-restore

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'web-app-actions'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_41E1FB9690374C03870777D5D0918133 }}
