name: .NET
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Restore do Projeto de API
        run: dotnet restore ./src/JornadaMilhas.API
      - name: Restore do Projeto de Dados
        run: dotnet restore ./src/JornadaMilhas.Dados
      - name: Restore do Projeto de Domínio
        run: dotnet restore ./src/JornadaMilhas.Dominio
      - name: Build projeto de API
        run: dotnet build ./src/JornadaMilhas.API --no-restore
      - name: Build projeto de Dados
        run: dotnet build ./src/JornadaMilhas.Dados --no-restore
      - name: Build projeto de Domínio
        run: dotnet build ./src/JornadaMilhas.Dominio --no-restore
      - name: Test da API
        run: dotnet test ./test/JornadaMilhas.Unity.Test
      - name: Enviar e-mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Build Concluída'
          body: 'Sua build foi concluída com sucesso!' 
          to: andrebessax@gmail.com
